In [3]:
1+1

2

In [4]:
a = 10

In [5]:
a+1

11

In [7]:
"This is a regular Text"

'This is a regular Text'

# The largest heading
## The second largest heading
###### The smallest heading

In the words of Abraham Lincoln:

> Pardon my French

In [9]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
import numpy

In [12]:
distances = [10, 15, 17]
times = [0.3, 0.47, 0.55]
distances = numpy.array(distances)
times = numpy.array(times)

In [13]:
speeds = distances / times

In [14]:
speeds

array([33.33333333, 31.91489362, 30.90909091])

In [15]:
speeds.sum()

96.15731785944553

In [16]:
x = numpy.arange(start=0, stop=20, step=2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
x + 1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
numpy.sin(x)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [19]:
numpy.sqrt(x)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

# Indexing

In [21]:
one_dim = numpy.linspace(-0.5, 0.6, 12)
one_dim

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [22]:
one_dim[0]

-0.5

In [23]:
two_dim = numpy.array([[3,5,2,4], [7,6,5,5], [1,6,-1,-1]])
two_dim

array([[ 3,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [24]:
two_dim[0,3]

4

# Slicing

In [26]:
one_dim[2:5]

array([-0.3, -0.2, -0.1])

In [27]:
two_dim[:2,:2]

array([[3, 5],
       [7, 6]])

In [30]:
two_dim[:,:2]

array([[3, 5],
       [7, 6],
       [1, 6]])

# Reshape

In [33]:
one_dim

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [34]:
one_dim.reshape(4,3)

array([[-0.5, -0.4, -0.3],
       [-0.2, -0.1,  0. ],
       [ 0.1,  0.2,  0.3],
       [ 0.4,  0.5,  0.6]])

In [35]:
two_dim

array([[ 3,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [36]:
two_dim.flatten()

array([ 3,  5,  2,  4,  7,  6,  5,  5,  1,  6, -1, -1])

# Coin Flips

In [45]:
numpy.random.randint(low=0, high=2, size=1)

array([1])

In [49]:
experiment = numpy.random.randint(low=0, high=2, size=10)
print(experiment)
print(experiment.sum())

[0 1 1 1 1 0 1 1 0 1]
7
